version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: arifkhan
      MYSQL_ROOT_PASSWORD: arifkhan
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://cinema_user:arifkhan@db/cinema_db
      FLASK_ENV: production
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db-data:
