version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cinema_db
      MYSQL_USER: cinema_user
      MYSQL_PASSWORD: arifkhan
      MYSQL_ROOT_PASSWORD: arifkhan
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cinema-local-network

volumes:
  db-data:

networks:
  cinema-local-network:
    driver: bridge
